[package]
name = "logic_model"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "logic_model"

[dependencies]
dotenv = "0.15.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
