[package]
name = "logic_model"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "logic_model"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.11.6"
log = "0.4.25"
